#server:
#  port: 8888
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    nacos:
#      discovery:
#
#        server-addr: 127.0.0.1:8848
#    gateway:
#
#      routes: #数组形式
#        - id: order-service  #路由唯一标识,一般写想要转发到服务名称
#          uri: lb: xdclass-order-service  #想要转发到的地址，转发到订单服务
##          uri: http://127.0.0.1:8000  #想要转发到的地址，转发到订单服务
#          order: 1 #优先级，数字越小优先级越高
#          predicates: #断言 配置哪个路径才转发
#            - Path=/order-server/**
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1  #去掉第一层前缀
#      discovery:
#        locator:
#          enabled: true
## - StripPrefix=1  #去掉第一层前缀http://localhost:8000/order-server/api/v1/video_order/list 把/order-server去掉就变成之前的地址了
##访问路径 http://localhost:8888/order-server/api/v1/video_order/list
##转发路径 http://localhost:8000/order-server/api/v1/video_order/list
##之前地址 http://localhost:8000/api/v1/video_order/list
##需要过滤器去掉前面第一层
#
##数组的形式
##        - id: video-service  #路由唯一标识
##            uri: http://127.0.0.1:8001  #想要转发到的地址
##            order: 1 #优先级，数字越小优先级越高
##            predicates: #断言 配置哪个路径才转发
##              - Path=/order-server/**
##            filters: #过滤器，请求在传递过程中通过过滤器修改
##              - StripPrefix=1  #去掉第一层前缀http://localhost:8000/order-server/api/v1/video_order/list 把/order-server去掉就变成之前的地址了
#

#
#server:
#  port: 8888
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#gateway:
#  routes: #数组形式
#    - id: order-service  #路由唯一标识
#      #uri: http://127.0.0.1:8000  #想要转发到的地址
#      uri: lb://xdclass-order-service  # 从nacos获取名称转发,lb是负载均衡轮训策略
#
#predicates: #断言 配置哪个路径才转发
#  - Path=/order-server/**
#filters: #过滤器，请求在传递过程中通过过滤器修改
#  - StripPrefix=1 #去掉第一层前缀
#discovery:
#  locator:
#    enabled: true  #开启网关拉取nacos的服务
#
### 访问路径 http://localhost:8888/order-server/api/v1/video_order/list
#
